[phases.build]
cmds = ["pip install -r BUILDER_TERMINAL_requirements.txt"]

[phases.start]
cmd = "gunicorn BUILDER_TERMINAL_API:app --bind 0.0.0.0:$PORT --timeout 120"

[variables]
PYTHON_VERSION = "3.11"
